AppTitle: 'Simple R Shiny Wizard App'
AppSubTitle: 'Simple R Shiny Wizard App'
WindowTitle: 'Simple R Shiny Wizard App'
LogoVisible: TRUE
LogoFilename: 'logo.png'
LogoWidht: 60
LogoHeight: 60
ShinyTheme: "flatly" 
NavTabName: "⚪"
NavTabElementsName: "Intro; StepI; Step II; Step III"
ShowButtons: TRUE
ButtonsAlignment: "center"

