# --- App Titles ---
AppTitle: "Shiny Wizard App"    # when "" is not displayed !!!
AppSubTitle: "Shiny Wizard App" # when "" is not displayed !!!
# --- CSS style ---
ShinyWizzardTheme: "flatly"
# --- Logo ---
LogoFilePath: "img/logo.png"  # when "" is not displayed !!!
LogoStyle: "height: 60px; wigth:60px; float:right; vertical-align:middle"
# --- Navigation ---
NavTabName: "⚪"
# --- Next/Prev buttons
ShowButtons: TRUE
ButtonsAlignment: "center" # left, right
ButtonsStyle: "position: fixed; padding: 10px 30px 50px 10px; bottom: 0; width: 100%; background: inherited;"
# --- Footer ---
FooterText: ""



