# --- App Titles ---
AppTitle: 'Shiny Wizard App'
AppSubTitle: 'Shiny Wizard App'
WindowTitle: 'Shiny Wizard App'
# --- CSS style ---
ShinyTheme: "darkly" # Also try one of #https://github.com/rstudio/shinythemes
CustomCSS: ""
# --- Logo ---
LogoVisible: TRUE
LogoFilePath: 'img/logo.png'
LogoStyle: "height: 60px; wigth:60px; float:right; vertical-align:middle"
# --- Navigation ---
NavTabName: "⚪"
# --- Next/Prev buttons
ShowButtons: TRUE
ButtonsAlignment: "center" # left, right
ButtonsStyle: "position: fixed; padding: 10px 30px 50px 10px; bottom: 0; width: 100%; background: white;"
# --- Footer ---
FooterVisible: TRUE
FooterHTML: "<i>Copyrights <b>© 2022</b> by the author</i>"
FooterStyle: "position: fixed; padding: 10px 30px 10px 10px; bottom: 0; height: 30; width: 100%; background: white; text-align: right;"



