# --- App Titles ---
AppTitle: "Shiny Wizard App"    # when "" is not displayed !!!
AppSubTitle: "Shiny Wizard App" # when "" is not displayed !!!
# --- CSS style ---
ShinyWizzardTheme: "flatly"
# --- Logo ---
LogoFilePath: img/logo.png  # when "" is not displayed !!!
# --- Navigation ---
NavTabName: "⚪"
# --- Footer ---
FooterText: ""
